auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # rook
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: liuxincuit/kube-state-metrics
  k8s.gcr.io/ingress-nginx/controller: liuxincuit/nginx-ingress-controller
