auth:
  registry.cn-chengdu.aliyuncs.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # rook
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: registry.cn-chengdu.aliyuncs.com/liuxin-registry/kube-state-metrics
